In [0]:
import pandas as pd

roller = pd.read_csv('rollercoaster.csv')
roller.columns = roller.columns.str.strip()
roller = roller.rename(columns={"Height (feet)":"Height"})
roller.loc[111, 'Height'] = 200
roller = roller [0:300]
roller['Duration (min:sec)'] = roller['Duration (min:sec)'].fillna('0:00')
roller['Duration (min:sec)'] = roller['Duration (min:sec)'].replace(' ','0:00')
roller['Length (feet)'] = roller['Length (feet)'].fillna(0)
roller['Height'] = roller['Height'].astype(float)
roller.columns

Index(['Name', 'Park', 'City/Region', 'City/State/Region', 'Country/Region',
       'Geographic Region', 'Construction', 'Type', 'Status',
       'Year/Date Opened', 'Height', 'Speed (mph)', 'Length (feet)',
       'Inversions (YES or NO)', 'Number of Inversions', 'Drop (feet)',
       'Duration (min:sec)', 'G Force', 'Vertical Angle (degrees)'],
      dtype='object')

In [0]:
#DURATION
def mintosec(time):
    new = time.split(':')
    seconds = (int(new[0])*60) + int(new[1])
    return seconds

rollerduration = roller['Duration (min:sec)']
def duration(rollerduration):
    seconds = mintosec(rollerduration)
    if seconds <=70:
        durationpoints = 1
    elif 70 < seconds <= 140:
        durationpoints = 2
    elif 140 < seconds <= 210:
        durationpoints = 3
    elif 210 < seconds <= 280:
        durationpoints = 4
    elif 280 < seconds <= 350:
        durationpoints = 5
    return durationpoints

roller['duration rating'] = roller['Duration (min:sec)'].apply(duration)

In [0]:
#LENGTH
rollerlength = roller['Length (feet)']
def length(rollerlength):
        if rollerlength <= 1650:
            lengthpoints = 1
        elif 1650 < rollerlength <= 3330:
            lengthpoints = 2
        elif 3330 < rollerlength <= 4980:
            lengthpoints = 3
        elif 4980 < rollerlength <= 6630:
            lengthpoints = 4
        elif 6630 < rollerlength <= 8280:
            lengthpoints = 5
        return lengthpoints
roller['length rating'] = roller['Length (feet)'].apply(length)

In [0]:
#SPEED
rollerspeed=roller['Speed (mph)']
def speed(rollerspeed):
    points = 0
    
    if 25 <= rollerspeed < 50:
        points += 1
    if 50 <= rollerspeed < 75:
        points += 2
    if 75 <= rollerspeed < 100:
        points += 3
    if 100 <= rollerspeed < 125:
        points += 4
    if 125 <= rollerspeed:
        points += 5   
    return points
roller['speed rating'] = roller['Speed (mph)'].apply(speed)

In [0]:
#AGE
rollerage = roller['Year/Date Opened']
def years(rollerage):
    points = 0
    if rollerage >= 2000:
        points += 5
    if 1980 <= rollerage < 2000:
        points += 4
    if 1960 <= rollerage < 1980:
        points += 3
    if 1940 <= rollerage < 1960:
        points += 2
    if 1920 <= rollerage < 1940:
        points += 1
    if rollerage == 'NaN':
        points += 0
    return points
        
roller['age rating'] = roller['Year/Date Opened'].apply(years)

In [0]:
#HEIGHT
rollerheight=roller['Height']


def Height(rollerheight):
    
    points = 0

    if rollerheight < 100 :
        points += 1
    if 100 <= rollerheight <  200 :
        points += 2
    if 200 <= rollerheight <  300 :
        points += 3
    if 300 <= rollerheight <  400 :
        points += 4
    if 400 <= rollerheight <  500 :
        points += 5
    return points

roller['height rating'] = roller['Height'].apply(Height)

In [0]:
#INVERSIONS
rollerinversions=roller['Number of Inversions']
def Inversions(rollerinversions):   
    points = 0
    if rollerinversions == 0:
        points += 0
    if 1 <= rollerinversions < 3 :
        points += 1
    if 3 <= rollerinversions < 6 :
        points += 2
    if 6 <= rollerinversions < 9 :
        points += 3
    if 9 <= rollerinversions < 12 :
        points += 4
    if 12 <= rollerinversions:
        points += 1
    return points
roller['inversions rating'] = roller['Number of Inversions'].apply(Inversions)

In [0]:
def finalrating(rollerspeed,rollerage, rollerduration,rollerheight,rollerinversions):
    totalrating = rollerage + rollerspeed + rollerduration + rollerheight + rollerinversions
    return totalrating
roller['total rating'] = roller['age rating']+roller['speed rating']+roller['length rating'] + roller['height rating'] + roller['inversions rating']

In [0]:
roller.sort_values(by='total rating',ascending = False)

,Name,Park,City/Region,City/State/Region,Country/Region,Geographic Region,Construction,Type,Status,Year/Date Opened,...,Duration (min:sec),G Force,Vertical Angle (degrees),duration rating,length rating,speed rating,age rating,height rating,inversions rating,total rating
239,Steel Dragon 2000,Nagashima Spa Land,Nagashima,"Kuwana,, Mie",Japan,Asia,Steel,Sit Down,Operating,2000.0,...,4:00,,NaN,4,5,3,5,4,0,17
146,Kingda Ka,Six Flags Great Adventure,Jackson,New Jersey,United States,North America,Steel,Sit Down,Operating,2005.0,...,0:28,NaN,90.0,1,2,5,5,5,0,17
131,Intimidator 305,Kings Dominion,Doswell,Virginia,United States,North America,Steel,Sit Down,Operating,2010.0,...,3:00,NaN,85.0,3,4,3,5,4,0,16
151,Leviathan,Canada's Wonderland,Vaughan,Onterio,Canada,North America,Steel,Sit Down,Operating,2012.0,...,3:28,NaN,80.0,3,4,3,5,4,0,16
103,Fury 325,Carowinds,Charlotte,North Carolina,United States,North America,Steel,Sit Down,Operating,2015.0,...,0:00,NaN,81.0,1,4,3,5,4,0,16
231,Soaring Dragon & Dancing Phoenix,Nanchang Wanda Theme Park,Xinjian,"Nanchang, Jiangxi",China,Asia,Steel,Inverted,Operating,2016.0,...,0:00,NaN,NaN,1,3,3,5,2,3,16
79,Eejanaika,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,Asia,Steel,Wing,Operating,2006.0,...,2:10,NaN,NaN,2,3,3,5,3,2,16
73,Dinoconda,China Dinosaurs Park,Xinbei,"Changzhou, Jiangsu",China,Asia,Steel,Wing,Operating,2012.0,...,0:00,NaN,NaN,1,3,3,5,3,2,16
242,Steel Vengeance,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Sit Down,Operating,2018.0,...,2:30,NaN,90.0,3,4,2,5,3,2,16
273,Top Thrill Dragster,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Sit Down,Operating,2003.0,...,0:30,NaN,90.0,1,2,4,5,5,0,16
280,Valravn,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Sit Down,Operating,2016.0,...,0:00,NaN,90.0,1,3,3,5,3,2,16
99,Formula Rossa,Ferrari World Abu Dhabi,Abu Dhabi,Abu Dhabi,United Arab Emirates,Middle East,Steel,Sit Down,Operating,2010.0,...,0:00,NaN,NaN,1,4,5,5,2,0,16
163,Millennium Force,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Sit Down,Operating,2000.0,...,2:20,NaN,80.0,2,4,3,5,4,0,16
253,Superman the Ride,Six Flags New England,Agawam,Massachusetts,United States,North America,Steel,Sit Down,Operating,2000.0,...,2:35,NaN,NaN,3,4,3,5,3,0,15
78,Dragon's Run,Dragon Park,Ha Long,Quang Ninh,Vietnam,Asia,Steel,Sit Down,Operating,2017.0,...,0:00,NaN,NaN,1,3,2,5,2,3,15
221,Shambhala,PortAventura Park,Salou,Tarragona,Spain,Europe,Steel,Sit Down,Operating,2012.0,...,3:00,3.8,NaN,3,4,3,5,3,0,15
74,Do-Dodonpa,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,Asia,Steel,Sit Down,Operating,2001.0,...,0:00,NaN,NaN,1,3,4,5,2,1,15
270,Titan,Six Flags Over Texas,Arlington,Texas,United States,North America,Steel,Sit Down,Operating,2001.0,...,3:30,NaN,NaN,3,4,3,5,3,0,15
6,Altair,Cinecittà World,Rome,Rome,Italy,Europe,Steel,Sit Down,Operating,2014.0,...,0:00,NaN,NaN,1,2,2,5,2,4,15
72,Diamondback,Kings Island,Kings Mills,Ohio,United States,North America,Steel,Sit Down,Operating,2009.0,...,3:00,NaN,NaN,3,4,3,5,3,0,15
71,Desperado,Buffalo Bill's Resort & Casino,Primm,Nevada,United States,North America,Steel,Sit Down,Operating,2005.0,...,2:43,4,60.0,3,4,3,5,3,0,15
219,Scream!,Six Flags Magic Mountain,Valencia,California,United States,North America,Steel,Sit Down,Operating,2003.0,...,3:00,NaN,NaN,3,3,2,5,2,3,15
127,Hyperion,Energylandia,Zator,Malopolskie,Poland,Europe,Steel,Sit Down,Operating,2018.0,...,0:00,4.8,85.0,1,3,3,5,3,1,15
100,Fujiyama,Fuji-Q Highland,Fujiyoshida,Yamanashi,Japan,Asia,Steel,Sit Down,Operating,1996.0,...,3:36,3.5,65.0,4,5,3,4,3,0,15
130,Intimidator,Carowinds,Charlotte,North Carolina,United States,North America,Steel,Sit Down,Operating,2010.0,...,3:33,NaN,74.0,4,4,3,5,3,0,15
218,Schwur des Kärnan,Hansa Park,Sierksdorf,Schleswig-Holstein,Germany,Europe,Steel,Sit Down,Operating,2015.0,...,0:00,NaN,NaN,1,3,3,5,3,1,15
65,Crazy Coaster,Loca Joy Holiday Theme Park,Yongchuan,Chongqing,China,Asia,Steel,Sit Down,Operating,2013.0,...,0:00,NaN,NaN,1,2,2,5,2,4,15
124,Helix,Liseberg,Gothenburg,Vastra Gotaland,Sweden,Europe,Steel,Sit Down,Operating,2014.0,...,2:10,4.3,NaN,2,3,2,5,2,3,15
250,Superman / la Atracción de Acero,Parque Warner Madrid,San Martin de la Vega,Madrid,Spain,Europe,Steel,Sit Down,Operating,2002.0,...,2:26,NaN,NaN,3,3,2,5,2,3,15
252,Superman Krypton Coaster,Six Flags Fiesta Texas,San Antonio,Texas,United States,North America,Steel,Sit Down,Operating,2000.0,...,2:35,NaN,NaN,3,3,2,5,2,3,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,Journey to Atlantis,SeaWorld San Diego,San Diego,California,United States,North America,Steel,Sit Down,Operating,2004.0,...,5:25,3,NaN,5,1,1,5,1,0,8
214,Road Runner Express,Six Flags Fiesta Texas,San Antonio,Texas,United States,North America,Steel,Sit Down,Operating,1997.0,...,2:24,NaN,NaN,3,2,1,4,1,0,8
185,Oblivion,Alton Towers,Alton,"Staffordshire, England",United Kingdom,Europe,Steel,Sit Down,Operating,1998.0,...,1:15,4.5,87.0,2,1,2,4,1,0,8
139,Journey to Atlantis,SeaWorld San Antonio,San Antonio,Texas,United States,North America,Steel,Sit Down,Operating,2007.0,...,3:30,NaN,NaN,3,1,0,5,2,0,8
296,Winjas,Phantasialand,Bruhl,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,2002.0,...,0:00,NaN,NaN,1,1,1,5,1,0,8
140,Judge Roy Scream,Six Flags Over Texas,Arlington,Texas,United States,North America,Wood,Sit Down,Operating,1980.0,...,1:30,NaN,NaN,2,2,1,4,1,0,8
12,Atlantica SuperSplash,Europa Park,Rust,Baden Wuerttemberg,Germany,Europe,Steel,Sit Down,Operating,2005.0,...,3:20,NaN,NaN,3,1,1,5,1,0,8
121,Half Pipe,Elitch Gardens,Denver,Colorado,United States,North America,Steel,Sit Down,Operating,2004.0,...,2:00,4.5,NaN,2,1,1,5,1,0,8
223,Sidewinder,Elitch Gardens,Denver,Colorado,United States,North America,Steel,Sit Down,Operating,1995.0,...,1:06,4,NaN,1,1,1,4,1,1,8
133,Iron Dragon,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Suspended,Operating,1987.0,...,2:00,NaN,NaN,2,2,1,4,1,0,8
189,Pandemonium,Six Flags Over Texas,Arlington,Texas,United States,North America,Steel,Sit Down,Operating,2008.0,...,1:51,NaN,NaN,2,1,1,5,1,0,8
33,Big Thunder Mountain Railroad,Disneyland,Anaheim,California,United States,North America,Steel,Sit Down,Operating,1979.0,...,3:00,NaN,NaN,3,2,1,3,2,0,8
82,Eurosat Can Can Coaster,Europa Park,Rust,Baden Wuerttemberg,Germany,Europe,Steel,Sit Down,Operating,1989.0,...,3:18,4,NaN,3,2,1,4,1,0,8
170,Montana Rusa,VulQano Park,Quito,Pichincha,Ecuador,South America,Steel,Sit Down,Operating,2005.0,...,0:00,NaN,NaN,1,1,0,5,1,1,8
206,Raven,Holiday World,Santa Claus,Indiana,United States,North America,Wood,Sit Down,Operating,1995.0,...,1:30,NaN,NaN,2,2,1,4,1,0,8
64,Crazy Bird,Happy Valley,Dongli,Tianjin,China,Asia,Steel,Sit Down,Operating,2013.0,...,0:00,NaN,120.0,1,1,0,5,1,1,8
247,Super Tornado,Zoo Safari- und Hollywoodpark Stukenbrock,Stukenbrock,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,1981.0,...,0:00,NaN,NaN,1,1,1,4,1,1,8
169,Montana Rusa,Salitre Magico,Bogota,Cundinamarca,Colombia,South America,Steel,Sit Down,Operating,2000.0,...,1:10,NaN,NaN,1,1,0,5,1,1,8
193,Phoenix,Knoebels Amusement Park,Elysburg,Pennsylvania,United States,North America,Wood,Sit Down,Operating,1985.0,...,2:00,NaN,NaN,2,2,1,4,1,0,8
235,Stampida,PortAventura Park,Salou,Tarragona,Spain,Europe,Wood,Sit Down,Operating,1997.0,...,1:40,NaN,NaN,2,2,1,4,1,0,8
234,SpeedSnake FREE,Fort Fun Abenteuerland,Wasserfall,North Rhine-Westphalia,Germany,Europe,Steel,Sit Down,Operating,1982.0,...,1:00,NaN,NaN,1,1,1,4,1,1,8
188,Pandemonium,Six Flags Fiesta Texas,San Antonio,Texas,United States,North America,Steel,Sit Down,Operating,2007.0,...,0:00,NaN,NaN,1,1,1,5,1,0,8
289,Whizzer,Six Flags Great America,Gurnee,Illinois,United States,North America,Steel,Sit Down,Operating,1976.0,...,2:00,NaN,NaN,2,2,1,3,1,0,7
66,Cyclone,Lakeside Amusement Park,Denver,Colorado,United States,North America,Wood,Sit Down,Operating,1940.0,...,2:00,NaN,50.0,2,2,2,2,1,0,7
38,Blue Streak,Cedar Point,Sandusky,Ohio,United States,North America,Wood,Sit Down,Operating,1964.0,...,1:45,NaN,NaN,2,2,1,3,1,0,7
261,Taunusblitz,Taunus Wunderland,Schlangenbad,Hesse,Germany,Europe,Steel,Sit Down,Operating,1999.0,...,1:50,NaN,NaN,2,1,1,4,1,0,7
55,Cedar Creek Mine Ride,Cedar Point,Sandusky,Ohio,United States,North America,Steel,Steel,Operating,1969.0,...,2:42,NaN,NaN,3,2,1,3,1,0,7
108,Giant Dipper,Santa Cruz Beach Boardwalk,Santa Cruz,California,United States,North America,Wood,Sit Down,Operating,1924.0,...,1:52,NaN,NaN,2,2,2,1,1,0,6
109,Giant Dipper,Belmont Park,San Diego,California,United States,North America,Wood,Sit Down,Operating,1925.0,...,0:00,NaN,NaN,1,2,2,1,1,0,6
57,Coaster Thrill Ride,Puyallup Fair,Puyallup,Washington,United States,North America,Wood,Sit Down,Operating,1935.0,...,1:45,NaN,NaN,2,2,2,1,1,0,6